[package]
name = "OrderNinja"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version="0.5.1", features = [ "json", "serde_json", "uuid", "secrets" ] }
diesel = { version = "=2.1.2, <2.1.3", features = ["postgres", "sqlite", "chrono", "uuid" ] }
